### ISSUE TITLE
中国大学MOOC无法下载

### ISSUE THREAD

**Issue by 121786404** [Foair/course-crawler#19]
## （错误简述）

网站：中国大学MOOC

课程地址：https://www.icourse163.org/course/NJUST-1001755037?tid=1003279008

问题描述：无法下载

D:\Program\course-crawler>python mooc.py https://www.icourse163.org/course/NJUST-1001755037?tid=1003279008 -d "G:\MOOCs"
计算机网络基础及应用 - 南京理工大学
第一单元  计算机网络导论（5个教学视频，5个学生自主实验视频，时长56’54‘‘）
  1.1 计算机网络的定义及其发展（1个视频，时长10’26‘’）
    【视频】计算机网络的定义及其发展——教学视频
    【文档】计算机网络的定义及其发展——PPT
    【富文本】计算机网络的定义及其发展——视频内容
Traceback (most recent call last):
  File "mooc.py", line 87, in <module>
    main()
  File "mooc.py", line 62, in main
    icourse163.start(args.url, config)
  File "D:\Program\course-crawler\mooc\icourse163.py", line 175, in start
    get_resource(course_info[0])
  File "D:\Program\course-crawler\mooc\icourse163.py", line 134, in get_resource
    params = {'nosKey': re.search('nosKey":"(.+?)"', text[3]).group(1),
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by SigureMo** [comment]
* 该问题前两天已在我的branch下解决（[最近一次commit](https://github.com/SigureMo/course-crawler/commit/49554a2cbbbc64fb7986c3bfc04b1830b26c4797)），请参照**该改动**对源文件进行更新即可  
* 我的branch下的icourse163.py有与原版本不太兼容的改动，暂时**不建议全部复制**，如果出现某些新课程无法下载的问题可以尝试
