### ISSUE TITLE
解析得到的中国大学MOOC下载地址无效

### ISSUE THREAD

**Issue by uilliu** [Foair/course-crawler#20]
## 解析得到的中国大学MOOC下载地址无效

网站：中国大学MOOC

课程地址：https://www.icourse163.org/course/USTC-9002?tid=1003097001

[问题描述：运行master分支代码出错：
Traceback (most recent call last):
  File "mooc.py", line 87, in <module>
    main()
  File "mooc.py", line 61, in main
    from mooc import icourse163
  File "D:\Git\course-crawler\mooc\icourse163.py", line 214, in <module>
    get_resource(course_info[0])
NameError: name 'course_info' is not defined
按照issues19](https://github.com/Foair/course-crawler/issues/19)提供的意见，修改了icourse163.py文件的一行之后，程序能够顺利解析该课程的下载地址。但是我将下载地址导入到迅雷、IDM、百度云，都无法下载。可能直链解析程序需要升级了，报告此问题，烦请抽空修复。

**Comment by SigureMo** [comment]
> 该问题的主要原因是课程太新，如果不是第一次开课而且如果对课程内容的新旧没有要求的话，可以尝试下前几次开课的视频（只是一个思路）

你好，我在十一已对该问题进行处理，该问题也是我在issues19所说的不要直接复制、与原作者不兼容的问题，既然该问题已经扩大，我在此对我的branch部分commit进行说明
* [Add cookies for icourse163](https://github.com/SigureMo/course-crawler/commit/2f90c4cec364986ba2937a4f84dd014b6c1b1f36)
该问题是我在十一发现某门新开课程（视频上传日期在2018/09/18左右，和你的2018/09/15相差不多）视频url无法打开，我对视频解析过程重新抓包发现网易对中M的视频接口进行了改动，不过该改动仅针对于比较新的视频，而且该解析过程需要cookies，emmm，就是说**旧接口不支持新视频，新接口支持所有视频但需要cookies**，所以我对icourse163增加了对cookies的支持，但考虑到大部分视频不需要新接口，所以我**保留了原有解析方式，只需要在要求输入cookies时候输入一个=就可以输入一个空cookies**，如若遇到你所说的那样的**新视频，请参照[网易云课堂MOOC的cookies注入方式](https://mooc.xoy.io/#/specific/study-163-mooc)对中Mcookies进行注入，便可获得真正的视频url**，该commit仅针对于2018/09附近及之后的视频url失效的问题，不能解决其余问题

* [Add open163](https://github.com/SigureMo/course-crawler/commit/f561ca7ec51245ed0e959374f0ecf10e8184f6af)
增加对网易公开课的支持

* 其他
其他分支大多是fix些小bug、做点小优化，没什么可提的，可以放心使用

由于最近联系不上原作者，所以如果有问题可以去我的[branch](https://github.com/SigureMo/course-crawler)下看下，我会在此后的一段时间内保证网易（icourse163、study163_mooc、study_163、open_163）部分课程的正常下载，但不会再去做新功能的支持（比如对付费功能破解的支持），真的没时间，请谅解

**Comment by sbkk000** [comment]
请问最近解析出来中国大学mooc的视频下载链接，放到网页里怎么都是404，找到了课程的cookies要怎么放入python命令中呢？

**Comment by alloai** [comment]
也碰到过同样的问题， 不过是把`http://v.stu.126.net/mooc-video/` 换成`https://jdvodrvfb210d.vod.126.net/jdvodrvfb210d/`
