### ISSUE TITLE
中国大学MOOC课程解析一半出错

### ISSUE THREAD

**Issue by ruoleng** [Foair/course-crawler#21]
## （错误简述）

网站：中国大学MOOC

课程地址：https://www.icourse163.org/course/NUEPU-292001?tid=1002962002

问题描述：课程分析完第三周 第二讲的【富文本】个性与职业的适配性选择报错
  Traceback (most recent call last):
  File "mooc.py", line 87, in <module>
    main()
  File "mooc.py", line 62, in main
    icourse163.start(args.url, config)
  File "...\course-crawler\mooc\icourse163.py", line 175, in start
    get_resource(course_info[0])
  File "..\course-crawler\mooc\icourse163.py", line 134, in get_resource
    params = {'nosKey': re.search('nosKey":"(.+?)"', text[3]).group(1),
AttributeError: 'NoneType' object has no attribute 'group

**Comment by ruoleng** [comment]
重新尝试了下载，又能完整解析了，没出错。

**Comment by ruoleng** [comment]
晕了，连续下几个课程搞混了。 这个课程还是有问题的，会报错上面的错，希望能看下原因 @Foair

**Comment by SigureMo** [comment]
请参考[issues19](19)
