### ISSUE TITLE
学堂在线下载提示错误

### ISSUE THREAD

**Issue by why05** [Foair/course-crawler#29]
## 学堂在线下载时，Traceback (most recent call last)

网站：学堂在线

课程地址：http://www.xuetangx.com/courses/course-v1:TsinghuaX+10430494X_2015_2+sp/about

问题描述：下载时提示错误：
E:\course-crawler-master> python mooc.py http://www.xuetangx.com/courses/course-v1:TsinghuaX+10430494X_2015_2+sp/about
验证成功！
大学物理2 (电磁学、光学和量子物理)(自主模式) - 清华大学
Traceback (most recent call last):
  File "mooc.py", line 87, in <module>
    main()
  File "mooc.py", line 66, in main
    xuetangx.start(args.url, config, cookies)
  File "C:\Users\why05\Downloads\Compressed\course-crawler-master_2\course-crawler-master\mooc\xuetangx.py", line 210, in start
    get_content(courseware)
  File "C:\Users\why05\Downloads\Compressed\course-crawler-master_2\course-crawler-master\mooc\xuetangx.py", line 70, in get_content
    chapters = soup.find(id='accordion').find_all(class_='chapter')
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by why05** [comment]
win10 专业版和ubuntu 18.04.1都试过
win10：Python 3.7.2
ubuntu：Python 3.6.7

**Comment by SigureMo** [comment]
出现该问题的话，主要应该是 cookies 的问题，可能是你的账号没有选择学习该课程

**Comment by why05** [comment]
好的，谢谢！
