### ISSUE TITLE
执行mooc.py报错

### ISSUE THREAD

**Issue by fatinghenji** [Foair/course-crawler#30]
## 执行mooc.py报错

网站：中国大学MOOC

课程地址：https://www.icourse163.org/course/SEU-1001752363

问题描述：
执行python mooc.py https://www.icourse163.org/course/SEU-1001752363报错
报错如下：
Traceback (most recent call last):
  File "mooc.py", line 87, in <module>
    main()
  File "mooc.py", line 61, in main
    from mooc import icourse163
  File "D:\中国大学mooc\course-crawler-master\mooc\icourse163.py", line 7, in <module>
    CANDY = Crawler()
  File "D:\中国大学mooc\course-crawler-master\mooc\utils.py", line 211, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)

**Comment by SigureMo** [comment]
不支持 python2 的 ， 请使用 python3

**Comment by LML-566** [comment]
> 不支持 python2 的 ， 请使用 python3

win10 python3.6 同样出现了此问题，望告知
