### ISSUE TITLE
程序运行出错

### ISSUE THREAD

**Issue by LML-566** [Foair/course-crawler#34]
## win10 python3.6 运行报错
测试的给出的命令行：python mooc.py https://www.icourse163.org/course/TONGJI-53004
运行出的错就是：
(py36) E:\MOOC Python\4-course-crawler-master\course-crawler-master>python mooc.py https://www.icourse163.org/course/TONGJI-53004
Traceback (most recent call last):
  File "mooc.py", line 87, in <module>
    main()
  File "mooc.py", line 61, in main
    from mooc import icourse163
  File "E:\MOOC Python\4-course-crawler-master\course-crawler-master\mooc\icourse163.py", line 7, in <module>
    CANDY = Crawler()
  File "E:\MOOC Python\4-course-crawler-master\course-crawler-master\mooc\utils.py", line 211, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
看之前的有人遇到这个问题，但回答的说是python2.X的原因，但我的是python3.6也遇到了这个错误。望告知

**Comment by SigureMo** [comment]
解决了？
