### ISSUE TITLE
学堂在线只能下载字幕，不能下载视频

### ISSUE THREAD

**Issue by why05** [Foair/course-crawler#36]
##  学堂在线只能下载字幕，不能下载视频

网站：学堂在线

课程地址：http://www.xuetangx.com/courses/course-v1:TsinghuaX+70240183x_1+sp/about

问题描述：python 3.7.3
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xuetangx.com', port=443): Max retries exceeded with url: /videoid2source/AC522B375B5714DE9C33DC5901307461 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mooc.py", line 87, in <module>
    main()
  File "mooc.py", line 66, in main
    xuetangx.start(args.url, config, cookies)
  File "F:\course-crawler-master\mooc\xuetangx.py", line 210, in start
    get_content(courseware)
  File "F:\course-crawler-master\mooc\xuetangx.py", line 139, in get_content
    parse_res_list(video_list, rename, playlist.write, get_video)
  File "F:\course-crawler-master\mooc\utils.py", line 337, in parse_res_list
    res.operation(*operator)
  File "F:\course-crawler-master\mooc\utils.py", line 56, in operation
    func(self)
  File "F:\course-crawler-master\mooc\xuetangx.py", line 49, in get_video
    res = CANDY.get('https://xuetangx.com/videoid2source/' + video.meta).text
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='xuetangx.com', port=443): Max retries exceeded with url: /videoid2source/AC522B375B5714DE9C33DC5901307461 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

**Comment by SigureMo** [comment]
该问题可以参考#33中的解决方案
