### ISSUE TITLE
好大学MOOC课程  没有视频下载地址等内容 

### ISSUE THREAD

**Issue by zhengguoouggnehz** [Foair/course-crawler#38]
## Videos.txt、Rename.bat、Outline.txt 等文件均没有内容

网站：https://www.cnmooc.org/home/index.mooc  （好大学在线CNMOOC)

课程地址：https://
www.cnmooc.org/portal/course/4687/13310.mooc

问题描述：E:\course-crawler-master\好大学>E:\course-crawler-master\好大学\mooc.py https://
www.cnmooc.org/portal/course/4687/13310.mooc
药理学 - 江苏大学
Traceback (most recent call last):
  File "E:\course-crawler-master\好大学\mooc.py", line 87, in <module>
    main()
  File "E:\course-crawler-master\好大学\mooc.py", line 77, in main
    cnmooc.start(args.url, config, cookies)
  File "E:\course-crawler-master\好大学\mooc\cnmooc.py", line 130, in start
    resource = get_resource(course_nav)
  File "E:\course-crawler-master\好大学\mooc\cnmooc.py", line 36, in get_resourc
e
    chapters = nav.find_all(class_='view-chapter')
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by SigureMo** [comment]
请确定你已经**登录**并**参加**该课程，并在此之后获取了 Cookies ，我这里一切正常

**Comment by zhengguoouggnehz** [comment]
已解决。感谢！
