### ISSUE TITLE
程序运行报错

### ISSUE THREAD

**Issue by HaggiCheng** [Foair/course-crawler#39]
下载完以后，仅有目录，没有视频链接 （请在这里填写错误简述）

网站：中国大学MOOC

课程地址：https://www.icourse163.org/course/TONGJI-53004 （网站中的示例地址）

问题描述：C:\Users\loli6\Desktop\course-crawler-master>python mooc.py https://www.icourse163.org/course/TONGJI-53004
高等数学（一） - 同济大学
第一周
  第一讲 函数与极限
    【视频】函数与初等函数
    【视频】数列及其极限
    【视频】收敛数列的性质
    【视频】自变量趋于有限值时函数的极限
    【视频】自变量趋于无穷大时函数的极限及函数极限的性质
    【文档】函数与初等函数课件
    【文档】函数的极限课件
    【文档】数列的极限课件
  第二讲 极限运算法则
    【视频】无穷小与无穷大
    【视频】极限的四则运算法则
    【视频】复合函数的极限运算法则
    【文档】无穷小与无穷大课件
    【文档】极限运算法则课件
第二周
  第三讲 两个重要极限和无穷小的比较
    【视频】极限存在准则I和重要极限I
    【视频】极限存在准则II和重要极限II
    【视频】无穷小比较的定义
    【视频】等价无穷小的性质
    【文档】极限存在准则，两个重要极限课件
    【文档】无穷小的比较课件
  第四讲 连续及其性质
    【视频】函数的连续性
    【视频】函数的间断点
    【视频】连续函数的运算
    【视频】初等函数的连续性
    【视频】闭区间上连续函数的性质
    【文档】函数的连续性与间断点课件
    【文档】连续函数的运算与初等函数的连续性课件
    【文档】闭区间上连续函数的性质课件
第三周
  第五讲 导数及其运算
    【视频】导数的定义1
    【视频】导数的定义2
    【视频】导数的定义3
    【视频】导数的几何意义
    【视频】导数的可导性与连续性的关系
    【视频】函数的和、差、积、商的求导法则
    【视频】反函数的求导法则
    【视频】复合函数的求导法则
    【文档】导数的概念课件
    【文档】函数的求导法则课件
  第六讲 高阶导数、隐函数与参数方程的导数
    【视频】高阶导数
    【视频】隐函数的导数
    【视频】由参数方程所确定的函数的导数
    【文档】高阶导数课件
    【文档】隐函数及由参数方程所确定的函数的导数课件
第四周
  第七讲 微分的概念与微分中值定理
    【视频】函数的微分
    【视频】罗尔定理I
    【视频】罗尔定理II
    【视频】拉格朗日中值定理
    【视频】柯西中值定理
    【文档】函数的微分课件
    【文档】微分中值定理与导数的应用课件
  第八讲 洛必达法则与泰勒公式
    【视频】用洛必达法则求“0/0”的未定式
    【视频】用洛必达法则求“∞/∞”的未定式
    【视频】用洛必达法则求其他类型的未定式
    【视频】泰勒公式I
    【视频】泰勒公式II
    【文档】洛必达法则课件
    【文档】泰勒公式课件
第五周
  第九讲 函数的单调性，凹凸性，极值与最值
    【视频】函数的单调性
    【视频】曲线的凹凸性
    【视频】函数的极值及其求法
    【视频】最大值最小值问题
    【文档】函数的单调性与曲线的凹凸性课件
    【文档】函数的极值与最大值最小值课件
  第十讲 函数图形的描绘与曲率
    【视频】函数图形的描绘
    【视频】曲率
    【文档】函数图形的描绘课件
    【文档】曲率课件
------> 1.1.1 函数与初等函数.mp4
Traceback (most recent call last):
  File "mooc.py", line 87, in <module>
    main()
  File "mooc.py", line 62, in main
    icourse163.start(args.url, config)
  File "C:\Users\loli6\Desktop\course-crawler-master\mooc\icourse163.py", line 175, in start
    get_resource(term_id)
  File "C:\Users\loli6\Desktop\course-crawler-master\mooc\icourse163.py", line 151, in get_resource
    parse_res_list(video_list, rename, parse_resource, playlist.write)
  File "C:\Users\loli6\Desktop\course-crawler-master\mooc\utils.py", line 337, in parse_res_list
    res.operation(*operator)
  File "C:\Users\loli6\Desktop\course-crawler-master\mooc\utils.py", line 56, in operation
    func(self)
  File "C:\Users\loli6\Desktop\course-crawler-master\mooc\icourse163.py", line 48, in parse_resource
    res_print(file_name + ext)
UnboundLocalError: local variable 'ext' referenced before assignment

这个是cmd窗口中的运行结果。 第一次使用GitHub，有描述不精确的地方，希望能够得到指导

**Comment by SigureMo** [comment]
看 #37 ，提 issue 前先看有没有相似 issue
