### ISSUE TITLE
中国大学MOOC下载报错

### ISSUE THREAD

**Issue by wangkun321** [Foair/course-crawler#43]
Traceback (most recent call last):
  File "D:\工作\MOOC\course-crawler-master\mooc.py", line 87, in <module>
    main()
  File "D:\工作\MOOC\course-crawler-master\mooc.py", line 62, in main
    icourse163.start(args.url, config)
  File "D:\工作\MOOC\course-crawler-master\mooc\icourse163.py", line 175, in start
    get_resource(term_id)
  File "D:\工作\MOOC\course-crawler-master\mooc\icourse163.py", line 151, in get_resource
    parse_res_list(video_list, rename, parse_resource, playlist.write)
  File "D:\工作\MOOC\course-crawler-master\mooc\utils.py", line 337, in parse_res_list
    res.operation(*operator)
  File "D:\工作\MOOC\course-crawler-master\mooc\utils.py", line 56, in operation
    func(self)
  File "D:\工作\MOOC\course-crawler-master\mooc\icourse163.py", line 48, in parse_resource
    res_print(file_name + ext)
UnboundLocalError: local variable 'ext' referenced before assignment

网站：中国大学MOOC

课程地址：（请在这里填写课程地址）

问题描述：（请在这里填写问题描述）

**Comment by StephanoGeorge** [comment]
#37
